Repository 107-systems/107-Arduino-Cyphal, pull requests merged in 2021-01, with the labels that each got.

#63 Allow configuration of heap size for o1heap
  extras/test/CMakeLists.txt
  src/ArduinoO1Heap.hpp
  src/ArduinoO1Heap.ipp
  src/ArduinoUAVCAN.cpp
  src/ArduinoUAVCAN.h
Labels: topic: firmware, type: enhancement

#64 Reintegrating all UAVCAN type logic into header-only implementation
  extras/test/CMakeLists.txt
  src/ArduinoUAVCANTypes.h
  src/types/uavcan/node/ExecuteCommand.1.0.Request.cpp
  src/types/uavcan/node/ExecuteCommand.1.0.Request.h
  src/types/uavcan/node/ExecuteCommand.1.0.Response.cpp
  src/types/uavcan/node/ExecuteCommand.1.0.Response.h
  src/types/uavcan/node/ExecuteCommand.1.0.h
  src/types/uavcan/node/Heartbeat.1.0.cpp
  src/types/uavcan/node/Heartbeat.1.0.h
  src/types/uavcan/node/ID.1.0.hpp
  src/types/uavcan/node/ID.1.0.ipp
  src/types/uavcan/node/Version.1.0.hpp
  src/types/uavcan/node/Version.1.0.ipp
  src/types/uavcan/primitive/scalar/Bit.1.0.hpp
  src/types/uavcan/primitive/scalar/Bit.1.0.ipp
Labels: topic: firmware, type: enhancement

#62 Replace pyuavcan-cli invocation with yakut commands in comments
  examples/UAVCAN-Blink/UAVCAN-Blink.ino
Labels: topic: documentation, type: enhancement

#67 Add CI workflow to do Arduino project-specific linting
  .github/workflows/arduino-lint.yml
  .github/workflows/extra-library-checks.yml
  README.md
Labels: topic: ci, type: enhancement

#65 Cleanup type headers in preparation for supporting all types.
  src/ArduinoUAVCANTypes.h
  src/types/uavcan/node/ExecuteCommand.1.0.Request.h
  src/types/uavcan/node/ExecuteCommand.1.0.h
  src/types/uavcan/node/ExecuteCommand.1.0.hpp
  src/types/uavcan/node/Health_1_0.h
  src/types/uavcan/node/Heartbeat.1.0.h
  src/types/uavcan/node/Heartbeat.1.0.hpp
  src/types/uavcan/node/Heartbeat.1.0.nnvg.h
  src/types/uavcan/node/ID.1.0.h
  src/types/uavcan/node/ID.1.0.hpp
  src/types/uavcan/node/Mode_1_0.h
  src/types/uavcan/node/Version.1.0.h
  src/types/uavcan/node/Version.1.0.hpp
  src/types/uavcan/primitive/scalar/Bit.1.0.hpp
  src/types/uavcan/primitive/scalar/Bit_1_0.h
Labels: priority: high, status: blocked, topic: firmware, type: enhancement
