Repository 107-systems/107-Arduino-Cyphal, pull requests merged in 2023-09, with the labels that each got.

#248 Integrate `libcanard` via `git subtree` and upgrade to libcanard/v3.1.1
  CMakeLists.txt
  src/libcanard/.clang-tidy
  src/libcanard/CMakeLists.txt
  src/libcanard/_canard_cavl.h
  src/libcanard/canard.c
  src/libcanard/canard.h
Labels: topic: firmware, type: enhancement

#250 Integrate libo1heap via git subtree and upgrade to libo1heap/v2.1.1
  CMakeLists.txt
  src/libo1heap/.clang-tidy
  src/libo1heap/CMakeLists.txt
Labels: topic: software, type: enhancement

#251 Move all CAN related examples into subfolder "CAN".
  .github/workflows/compile-examples.yml
  CMakeLists.txt
  examples/CAN/OpenCyphal-Blink/OpenCyphal-Blink.ino
  examples/CAN/OpenCyphal-Heartbeat-Publisher/OpenCyphal-Heartbeat-Publisher.ino
  examples/CAN/OpenCyphal-Heartbeat-Subscriber-With-Metadata/OpenCyphal-Heartbeat-Subscriber-With-Metadata.ino
  examples/CAN/OpenCyphal-Heartbeat-Subscriber/OpenCyphal-Heartbeat-Subscriber.ino
  examples/CAN/OpenCyphal-Service-Client/OpenCyphal-Service-Client.ino
  examples/CAN/OpenCyphal-Service-Server/OpenCyphal-Service-Server.ino
  examples/CAN/host-example-01-opencyphal-basic-node/.gitignore
  examples/CAN/host-example-01-opencyphal-basic-node/CMakeLists.txt
  examples/CAN/host-example-01-opencyphal-basic-node/README.md
  examples/CAN/host-example-01-opencyphal-basic-node/host-example-01-opencyphal-basic-node.cpp
  examples/CAN/host-example-01-opencyphal-basic-node/kv_host.cpp
  examples/CAN/host-example-01-opencyphal-basic-node/kv_host.h
  examples/CAN/host-example-01-opencyphal-basic-node/setup_vcan.sh
  examples/CAN/host-example-01-opencyphal-basic-node/setup_yakut.sh
  examples/CAN/host-example-01-opencyphal-basic-node/socketcan.c
  examples/CAN/host-example-01-opencyphal-basic-node/socketcan.h
Labels: topic: documentation, type: enhancement

#252 Add note concerning commercial support.
  README.md
Labels: topic: documentation

#254 Revert "Bump codecov/codecov-action from 3 to 4 (#253)"
  .github/workflows/unit-tests.yml
Labels: type: bug, topic: ci

#255 Rename OpenCyphalPicoBase to CyphalPicoBase/CAN.
  README.md
Labels: topic: documentation, type: enhancement

#256 Rename OpenCyphalServoController12 to CyphalServoController12/CAN
  README.md
Labels: topic: documentation, type: enhancement
